# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/PINOUT.xdc

# Block Designs: bd/ZynqLinuxSD/ZynqLinuxSD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqLinuxSD || ORIG_REF_NAME==ZynqLinuxSD} -quiet] -quiet

# IP: bd/ZynqLinuxSD/ip/ZynqLinuxSD_processing_system7_0_0/ZynqLinuxSD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqLinuxSD_processing_system7_0_0 || ORIG_REF_NAME==ZynqLinuxSD_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqLinuxSD/ip/ZynqLinuxSD_xlconcat_0_0/ZynqLinuxSD_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqLinuxSD_xlconcat_0_0 || ORIG_REF_NAME==ZynqLinuxSD_xlconcat_0_0} -quiet] -quiet

# IP: bd/ZynqLinuxSD/ip/ZynqLinuxSD_xlconcat_1_0/ZynqLinuxSD_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZynqLinuxSD_xlconcat_1_0 || ORIG_REF_NAME==ZynqLinuxSD_xlconcat_1_0} -quiet] -quiet

# XDC: bd/ZynqLinuxSD/ZynqLinuxSD_ooc.xdc
